{
 "title": "Styx System Overview",
 "tags": [
  "Styx",
  "General"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (worker_cpu_usage_percent)"
    }
   ]
  },
  {
   "title": "Memory Utilization (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (worker_memory_usage_mb) * 1000000"
    }
   ]
  },
  {
   "title": "Ingress Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(worker_network_rx_kb[5s])) * 1000"
    }
   ]
  },
  {
   "title": "Egress Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(worker_network_tx_kb[5s])) * 1000"
    }
   ]
  },
  {
   "title": "TPS (committed)",
   "type": "timeseries",
   "description": "Throughput per epoch of the committed transactions",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(worker_epoch_throughput_tps[15s]))"
    }
   ]
  },
  {
   "title": "Backpressure & Backlog",
   "type": "timeseries",
   "description": "Backpressure - number of input elements that have been consumed by styx but not yet processed\nBacklog - inputs that are in Kafka but aren't consumed by styx yet (cur_styx_offest - kakfa_end_offset)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "targets": [
    { "expr": "sum(queue_backlog)", "legendFormat": "__auto" },
    { "expr": "sum(worker_backpressure)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Num transactions per epoch",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "epoch_committed_lock_free > 0",
     "legendFormat": "lock_free_commited ({{exported_instance}})"
    },
    {
     "expr": "epoch_committed_fallback > 0",
     "legendFormat": "fallback_comitted ({{exported_instance}})"
    },
    {
     "expr": "epoch_logic_aborts > 0",
     "legendFormat": "logic_aborts ({{exported_instance}})"
    },
    {
     "expr": "epoch_concurrency_aborts > 0",
     "legendFormat": "concurrency_aborts ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Average Latency Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(latency_breakdown > 0) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Worker Utilisation",
   "type": "timeseries",
   "description": "Processing time / Total epoch time\nUsed to identify workers that are spending most of the time idle or on I/O tasks",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(worker_utilization[5s])",
     "legendFormat": "Utilisation ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "description": "Total latency of commited transactions",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(worker_epoch_latency_ms)" }
   ]
  },
  {
   "title": "Operator Execution time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg by (operator) (operator_latency_ms)",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Operator TPS",
   "type": "timeseries",
   "description": "TPS per operator -> calculated as operator execution time in the epoch / total epoch latency",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "avg by (operator) (operator_tps)",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Average Operator Call Count ",
   "type": "timeseries",
   "description": "Number of times a call goes through an operator during the epoch",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "avg by (operator) (operator_call_count)",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Snapshot Latency",
   "type": "timeseries",
   "description": "Total latency for taking a snapshot",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(worker_total_snapshotting_time_ms)"
    }
   ]
  },
  {
   "title": "Abort Rate (%)",
   "type": "timeseries",
   "description": "Percentage of aborted transactions",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(worker_abort_percent)" }
   ]
  },
  {
   "title": "Empty Epochs",
   "type": "status-history",
   "description": "1 if the epoch had no work (the input sequence is empty, the epoch was just syncing), 0 otherwise",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "avg_over_time(worker_empty_epoch[1s])",
     "legendFormat": "Worker: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Idle time (ms)",
   "type": "timeseries",
   "description": "Time the worker spent idle in each epoch",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "idle_time_ms_per_second",
     "legendFormat": "Idle time ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Time since last heartbeat (ms)",
   "type": "bargauge",
   "description": "Time since the last heartbeat for each worker",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time_since_last_heartbeat", "legendFormat": "{{exported_instance}}" }
   ]
  }
 ]
}